### ISSUE TITLE
AccessDenied! (attempting to send email on Lambda)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/aws-ses-lambda#10]
Attempting to run the Lambda function on Lambda getting the following error:
```
{
  "errorType": "AccessDenied",
  "errorMessage": "User `arn:aws:sts::123456789:assumed-role/LambdaExecRole/aws-ses-lambda-v1' is not authorized to perform `ses:SendEmail' on resource `arn:aws:ses:eu-west-1:123456789:identity/nelson@gmail.com'",
  "trace": [
    "AccessDenied: User `arn:aws:sts::123456789:assumed-role/LambdaExecRole/aws-ses-lambda-v1' is not authorized to perform `ses:SendEmail' on resource `arn:aws:ses:eu-west-1:123456789:identity/nelson@gmail.com'",
    "    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/query.js:50:29)",
    "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
    "    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
    "    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)",
    "    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
    "    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
    "    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
    "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
    "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)",
    "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
  ]
}
```

Investigating now ... 🔍

**Comment by nelsonic** [comment]
Turns out that the AWS related environment variables are _not_ included in the `.env` file that gets exported ... so we need a better way of doing this ... >> https://github.com/dwyl/aws-lambda-deploy/issues/58

**Comment by nelsonic** [comment]
Sadly, the environment variable approach is _not_ going to work because AWS blocks it!! 
See: dwyl/aws-lambda-deploy#58 (comment)
GOTO: https://github.com/dwyl/aws-ses-lambda/issues/11
